name: native_app
description: >
  A command line application that can be compiled to native code using
  dart2native.

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0

executables:
  main: hello_world
