name: native_app
description: >-
  A command line application that can be compiled to native code using
  dart compile exe.

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^3.0.0

executables:
  main: hello_world
