name: extension_methods
description: >-
  A set of use cases for the extension methods feature.

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ^3.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
