name: hello_world_ffi
version: 0.0.1
description: >-
  A super simple example of calling C code from Dart with FFI

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  test_utils:
    path: ../test_utils
