name: cloud_storage_example
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ^3.10.0

dependencies:
  google_cloud: ^0.5.0
  google_cloud_shelf: ^0.6.0
  google_cloud_storage: ^0.6.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  http: ^1.6.0
  lints: ^6.0.0
  test: ^1.27.0
  test_process: ^2.1.1
