dart:
  - dev
  - 2.12.0

os:
  - linux
  - macos
  - windows

stages:
  - analyze:
    - dartanalyzer: --fatal-infos .
      os: linux
    - dartfmt:
      os: linux
      dart: dev
  - unit_test:
    - test
