class MyJsonAnnotation {
  const MyJsonAnnotation();
}

@MyJsonAnnotation()
class Planet {
  final String name;
  final int size;

  const Planet(this.name, this.size);
}

// --- generated (assume the following is in a separate file, and autogenerated)

/// The following can now be generated by a package, making [Planet]
/// serializable with almost no effort from you, the developer.
///
/// Without extension methods, you would need to write things like:
///
///     // No longer needed!
///     Map<String, Object> toJson() => _$PlanetJsonifier(this);
extension PlanetExtensions on Planet {
  static Planet from(Map<String, Object> json) =>
      Planet(json['name'] as String, json['size'] as int);

  Map<String, Object> toJson() => {'name': name, 'size': size};
}
