dart:
  - dev
  - 2.12.0

stages:
  - analyze:
    - dartanalyzer: --fatal-infos .
    - dartfmt:
      dart: dev
# This sample uses a live Google API, so no unit tests are provided – yet
#  - unit_test:
#    - test
