name: system_command
description: A FFI application that invokes system commands.
version: 1.1.0
author: Michael Thomsen <mit@google.com>

environment:
  sdk: '>=2.12.0-259.12.beta <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  test: ^1.16.0

