name: system_command
description: A FFI application that invokes system commands.

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  ffi: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
