name: system_command
description: A FFI application that invokes system commands.

# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
