name: system_command
description: A FFI application that invokes system commands.
version: 1.0.0
author: Michael Thomsen <mit@google.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  ffi: ^1.0.0

dev_dependencies:
  test: ^1.5.3

